import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import NextTopLoader from "nextjs-toploader";
import { TriangleAlert } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Omar Shoe Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
                <NextTopLoader color="#2563EB" height={3} showSpinner={false}/>
                <div className="bg-red-100 border-l-4 border-red-500 text-red-700 p-4">
                    <p className="font-semibold flex items-center">
                        <TriangleAlert className="mr-2" />
                        Notice: You can access the dashboard because this is a learning project, you cant add, edit, or delete any thing in it.
                    </p>
                </div>
                {children}
            </body>
        </html>
    );
};