import React from 'react'
import DashboardNavigation from '../components/dashboard/DashboardNavigation';
import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet';
import { CircleUser, MenuIcon, TriangleAlert } from 'lucide-react';
import { DropdownMenu,DropdownMenuItem,DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server';
import { redirect } from 'next/navigation';
import { Button } from "@/components/ui/button";
import { LogoutLink} from "@kinde-oss/kinde-auth-nextjs/components";
import { Metadata } from 'next';


export const metadata: Metadata = {
    title: "Omar Shoe Dashboard",
    description: "Generated by create next app",
};

const DashboardLayout = async ({children,}: Readonly<{children: React.ReactNode}>) => {
    const { getUser } = getKindeServerSession();
    const user = await getUser();

    if(!user){
        return redirect('/');
    }

    return (
        <>
            <div className="bg-red-100 border-l-4 border-red-500 text-red-700 p-4">
                <p className="font-semibold flex items-center">
                    <TriangleAlert className="mr-2" />
                    Notice: You can access the dashboard because this is a learning project, you cant add, edit, or delete any thing in it.
                </p>
            </div>
            <div className='flex flex-col max-w-7xl mx-auto px-4 sm:px-6 lg:px-8'>
                <header className="sticky top-0 flex h-16 items-center justify-between gap-4 border-b bg-white">
                    <nav className="hidden font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6">
                        <DashboardNavigation/>
                    </nav>
                    <Sheet>
                        <SheetTrigger asChild>
                            <Button variant={"outline"} size={"icon"} className='shrink-0 md:hidden'>
                                <MenuIcon className='h-5 w-5'/>
                            </Button>
                        </SheetTrigger>
                        <SheetContent side={"left"}>
                            <nav className="flex flex-col gap-6 text-lg font-medium mt-5">
                                <DashboardNavigation/>
                            </nav>
                        </SheetContent>
                    </Sheet>
                    <DropdownMenu >
                        <DropdownMenuTrigger asChild>
                            <Button variant={"secondary"} size={"icon"} className='rounded-full'>
                                <CircleUser className='w-5 h-5'/>
                            </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align={"end"}>
                            <DropdownMenuLabel>My Account</DropdownMenuLabel>
                            <DropdownMenuSeparator/>
                            <DropdownMenuItem asChild className='cursor-pointer'>
                                <LogoutLink>Logout</LogoutLink>
                            </DropdownMenuItem>
                        </DropdownMenuContent>
                    </DropdownMenu>
                </header>
                <main className="my-5">
                    {children}
                </main>
            </div>
        </>
    );
};

export default DashboardLayout;
